### ISSUE TITLE
Reading on uninitialized buffer may cause UB

### ISSUE THREAD

**Issue by JOE1994** [AlexPikalov/cassandra-proto#3]
Hello :crab: ,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description
https://github.com/AlexPikalov/cassandra-proto/blob/9bdbc91e2eb6ec11a2bbe5c8d5f621bfc202b483/src/frame/parser_async.rs#L46-L51

https://github.com/AlexPikalov/cassandra-proto/blob/9bdbc91e2eb6ec11a2bbe5c8d5f621bfc202b483/src/frame/parser_async.rs#L65-L69

We found two cases where an uninitialized buffer is created (`body_bytes` & `tracing_bytes`) and passed to user-provided `Read` implementation. This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that `buf` is initialized before calling `read`. Calling read with an uninitialized `buf` (of the kind one obtains via `MaybeUninit<T>`) is not safe, and can lead to undefined behavior.

## Suggested Fix
It is safe to zero-initialize the newly allocated `u8` buffer before `read()`, in order to prevent user-provided Read from accessing old contents of the newly allocated heap memory.

Thank you for checking out this issue :+1:

**Comment by AlexPikalov** [comment]
Thank you @JOE1994
